# Generated by Django 2.0.4 on 2018-05-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='code',
            field=models.CharField(default='SA', max_length=32, null=True),
        ),
    ]
