# Generated by Django 2.0.4 on 2018-05-02 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_application_hosttoapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosttoapp',
            name='aobj',
        ),
        migrations.RemoveField(
            model_name='hosttoapp',
            name='hobj',
        ),
        migrations.DeleteModel(
            name='HostToApp',
        ),
    ]
