# Generated by Django 2.0.4 on 2018-05-02 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_application_r'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostToApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='r',
        ),
        migrations.AddField(
            model_name='hosttoapp',
            name='aobj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Application'),
        ),
        migrations.AddField(
            model_name='hosttoapp',
            name='hobj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Host'),
        ),
    ]
