# Generated by Django 2.0.4 on 2018-05-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20180503_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosttoapp',
            name='aobj',
        ),
        migrations.RemoveField(
            model_name='hosttoapp',
            name='hobj',
        ),
        migrations.AddField(
            model_name='application',
            name='r',
            field=models.ManyToManyField(to='app01.Host'),
        ),
        migrations.DeleteModel(
            name='HostToApp',
        ),
    ]
