# Generated by Django 2.0.4 on 2018-05-20 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20180521_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user_type',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
