# Generated by Django 2.0.4 on 2018-05-09 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInf',
            new_name='UserInfo',
        ),
    ]
