# Generated by Django 2.0.4 on 2018-05-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=32, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='u2g',
            field=models.ManyToManyField(to='publicapp.UserGroup'),
        ),
    ]
