# Generated by Django 2.0.4 on 2018-05-01 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_auto_20180501_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.UserGroup'),
        ),
    ]
